formats: 
  audio: 'mp3'
  video: 'mp4'
quality:
 audio: 0
 video: bestvideo+bestaudio/best
app:
  title: YouTube Downloader
  by: volpepe
  start_geometry:
    width: 700
    height: 450
  colors:
    bg: brown
    fg: white
  fonts:
    family: Arial
    size: 12
    weight: normal
  lang: IT